# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BillPaySdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BillPaySdk

  target 'BillPaySdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BillPaySdkUITests' do
    # Pods for testing
  end

end
